#! /bin/sh

bspc monitor eDP -d I II III IV
bspc monitor HDMI-A-0 -d V VI VII VIII

bspc config border_width 4
bspc config window_gap 8

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

killall -q picom
killall -q sxhkd
killall -q dunst
killall -q polybar
killall -q fcitx5

sleep 1

~/.fehbg
picom -b --experimental-backends
sxhkd &
dunst &
polybar main &
polybar second &
fcitx5 &

