#! /bin/sh

bspc monitor eDP -d I II III IV
bspc monitor HDMI-A-0 -d V VI VII VIII

bspc config border_width 4
bspc config window_gap 8

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

~/.fehbg
pgrep -x picom || picom -b --experimental-backends
pgrep -x sxhkd || sxhkd &
pgrep -x dunst || dunst &
polybar main -c ~/.config/polybar/config.ini &
polybar second -c ~/.config/polybar/config.ini &
fcitx5 &
